// Generated by CoffeeScript 1.9.3
(function() {
  var CoffeeScript, LiveScript, _, async, backbone, colors, fs, h, lego, loadSettings, path, util;

  path = require('path');

  async = require('async');

  backbone = require('backbone4000');

  colors = require('colors');

  _ = require('underscore');

  h = require('helpers');

  lego = require('lego');

  fs = require('fs');

  util = require('util');

  LiveScript = require('LiveScript');

  CoffeeScript = require('coffee-script');

  exports.init = function(env, callback) {
    var getVersion, loadLegos, remPw;
    if (env == null) {
      env = {};
    }
    _.extend(env, {});
    env.root = path.dirname(require.main.filename);
    env.settings = loadSettings(env.root, env.settings);
    console.log('initializing', env.root);
    if (env.settings.verboseInit) {
      remPw = h.depthFirst(env.settings, {}, function(val, key) {
        if (h.strHas(key, 'pass', 'secret', 'login')) {
          return h.uuid(15 + h.randomInt(15));
        } else {
          return val;
        }
      });
      console.log(util.inspect(remPw, {
        colors: true,
        depth: 4
      }));
    }
    getVersion = function(callback) {
      var gitrev;
      console.log('getver');
      gitrev = require('git-rev');
      return gitrev.short(function(str) {
        console.log('getver done');
        env.version = str;
        return callback();
      });
    };
    loadLegos = function(callback) {
      console.log('loadlegos');
      return lego.loadLegos({
        verbose: env.verbose,
        dir: env.settings.rootDir || h.path(env.root, 'node_modules'),
        prefix: 'ribcage_',
        env: env
      }, function(err, data) {
        console.log('loadlegos done');
        return callback(err, data);
      });
    };
    return async.series([getVersion, loadLegos], function(err, data) {
      return callback(err, env);
    });
  };

  loadSettings = function(folder, settings) {
    var fileSettings, settingsFile;
    if (settings == null) {
      settings = {};
    }
    settingsFile = h.path(folder, 'settings');
    if (fs.existsSync(settingsFile + ".js") || fs.existsSync(settingsFile + ".ls") || fs.existsSync(settingsFile + ".coffee")) {
      fileSettings = require(settingsFile);
      if (fileSettings.settings != null) {
        fileSettings = fileSettings.settings;
      }
      settings = h.extend(settings, fileSettings);
    }
    return settings;
  };

}).call(this);
