// Generated by CoffeeScript 1.7.1
(function() {
  var CoffeeScript, async, backbone, colors, fs, h, lego, loadSettings, path, util, _;

  path = require('path');

  CoffeeScript = require('coffee-script');

  async = require('async');

  backbone = require('backbone4000');

  colors = require('colors');

  _ = require('underscore');

  h = require('helpers');

  lego = require('lego');

  fs = require('fs');

  util = require('util');

  exports.init = function(env, callback) {
    var getVersion, loadLegos, remPw;
    if (env == null) {
      env = {};
    }
    _.extend(env, {});
    env.root = path.dirname(require.main.filename);
    env.settings = loadSettings(env.root, env.settings);
    if ((env.verboseInit == null) || env.verboseInit) {
      remPw = h.depthFirst(env.settings, {}, function(val, key) {
        if (h.strHas(key, 'pass', 'secret', 'login')) {
          return h.uuid(15 + h.randomInt(15));
        } else {
          return val;
        }
      });
      console.log(util.inspect(remPw, {
        colors: true
      }));
    }
    getVersion = function(callback) {
      var gitrev;
      gitrev = require('git-rev');
      return gitrev.short(function(str) {
        env.version = str;
        return callback();
      });
    };
    loadLegos = function(callback) {
      return lego.loadLegos({
        dir: h.path(env.root, 'node_modules'),
        prefix: 'ribcage_',
        env: env
      }, callback);
    };
    return async.series([getVersion, loadLegos], function(err, data) {
      return callback(err, env);
    });
  };

  loadSettings = function(folder, settings) {
    var settingsCoffee, settingsJs;
    if (settings == null) {
      settings = {};
    }
    settingsJs = h.path(folder, 'settings.js');
    if (fs.existsSync(settingsCoffee = h.path(folder, 'settings.coffee'))) {
      fs.writeFileSync(settingsJs, CoffeeScript.compile(String(fs.readFileSync(settingsCoffee))));
    }
    if (fs.existsSync(settingsJs)) {
      settings = h.extend(settings, require(settingsJs).settings);
    }
    return settings;
  };

}).call(this);
